### ISSUE TITLE
different units in provided example netcdf files

### ISSUE THREAD

**Issue by pradhancda** [pacificclimate/ClimDown#13]
Sir,

During analysis, found that the netcdf has different dimensions. such as 
1. co-ordinates of extent differs in both netcdf given in test folder
2. the units of tasmax differs

Please update ..........
can you please suggest, how to replace the header of the variables ?

regards,
Subhasis

**Comment by jameshiebert** [comment]
> 1. co-ordinates of extent differs in both netcdf given in test folder

That's not a problem. [The extent of the observation domain must only be a spatial subset of the GCM domain](https://github.com/pacificclimate/ClimDown/blob/master/R/CI.R#L157).

> 2. the units of tasmax differs

That's not a problem because the code [converts units from the input source to a user configured target unit](https://github.com/pacificclimate/ClimDown/blob/master/R/io.R#L18).
