### ISSUE TITLE
Error units not convertible for pr

### ISSUE THREAD

**Issue by ndichistan** [pacificclimate/ClimDown#26]
Hi,
I am trying to downscale a medium-resolution precipitation dataset into a higher resolution data. 
I am using a subset of my file to test the downscaling method and wrote the code below for it. Unfortunately, I get an error whenever i run my code. Could you check what is wrong with it? 
I have tried different units for daily precipitation to see which would be accepted without success. I have also attached the sample datasets used in the test case.

```
##Loading required libraries
library(ClimDown)
library(ncdf4)
library(tidyr)
library(tidync)
library(udunits2)

setwd('/projects/dgs/persad_research/Nduka_data/climateR')

test_output.nc <- tempfile(fileext='.nc')
options(
  calibration.start=as.POSIXct('2000-01-01', tz='GMT'),
  [calibration.end=as.POSIXct('2000-04-30',]([url]([pr_data.zip](https://github.com/pacificclimate/ClimDown/files/13492779/pr_data.zip))) tz='GMT')
)

ClimDown::bccaq.netcdf.wrapper('pr_day_CNRM-ESM2-1_historical_r1i1p1f2_gr_20000101.nc', 'pr_daily_20000104.nc', test_output.nc, 'pr')
unlink(test_output.nc)
```
The error is 
"Error in ud.convert(x, source.units, getOption("target.units")[varid]) : 
  Units mm and kg m-2 d-1 are not convertible"

[pr_data.zip](https://github.com/pacificclimate/ClimDown/files/13492795/pr_data.zip)

**Comment by corviday** [comment]
Hello. The issue is that your precipitation data is given in millimeters (`mm`). Climdown expects precipitation data to be formatted as kilograms per square meter per day (`kg m-2 d-1`). If it receives data that is not in kilograms per square meter per day, it will attempt to convert it using [udunits](https://www.unidata.ucar.edu/software/udunits/). However, udunits is not able to convert millimeters to kilograms per square meters per day, for two reasons:

* millimeters has no time component (to attempt to convert to the "per day" portion of the expected measurement)

* millimeters cannot automatically be converted to kilograms per square meter. It is true that liquid water to a depth of one millimeter of an area of one square meter would weigh a kilogram, but udunits has no way to know you are talking about _water_ and a millimeter deep across a square meter of some other substance would weight more or less, so it cannot make the conversion automatically

If you update the units of your precipitation data to something climdown can understand, it should run.

**Comment by ndichistan** [comment]
Thanks for the feedback.

**Comment by ndichistan** [comment]
Hi, 
I have implemented your suggestions and tried to make all the recommended changes, but has this new error (I don't know if it should be treated here or I should open a new issue for it).
The code is the same, the data has been modified (new data is attached). 

```
[1] "Calculating daily anomalies on the GCM"
[1] "vobjtovarid4: **** WARNING **** I was asked to get a varid for dimension named lat BUT this dimension HAS NO DIMVAR! Code will probably fail at this point"
Error in nc$dim[[idobj$list_index]] : 
  invalid negative subscript in get1index <real>
```
[pr_data_v2.zip](https://github.com/pacificclimate/ClimDown/files/13501854/pr_data_v2.zip)

**Comment by ndichistan** [comment]
@jameshiebert I experienced some more issues and wasn't sure if I am to post it here or not. I'll close this now. Thanks for all your help.
