### ISSUE TITLE
Some queries about the package

### ISSUE THREAD

**Issue by javakh** [pacificclimate/ClimDown#5]
I have just come through your package in R. I have previously used 'esd' package in R for downscaling in R.
I have some queries about your package so that I can use it in my work-
i) Does the functions work for a single point location i.e. single station?
ii) What variables can be downscaled by this package?
iii) I found the formats of GCM data required is netCDF; but what is the format required for observed data?
iv) For gridded observed data, would resolution of GCM and observed data required is the same?
v) I have not found any example in the manual.Can you please provide some examples about how to use the functions.

**Comment by jameshiebert** [comment]
Hi @javakh ,
The BCCAQ downscaling method that ClimDown implements is based on taking a gridded GCM and downscaling it to the spatial resolution of a gridded observations. So that fact informs a number of your questions:
i) No.
ii) Min temperature (tasmin), Max temperature (tasmax), precipitation (pr)
iii) netCDF as well
iv) No, presumably the resolution of the obs should be finer.
v) Page 2 of [the manual](https://cran.r-project.org/web/packages/ClimDown/ClimDown.pdf):
```R
bccaq.netcdf.wrapper(gcm.file, obs.file, out.file, varname = "tasmax")
```
Did you need something more detailed than that?
Hope that helps.

**Comment by javakh** [comment]
Thanks for your response.I have gridded observation in **.rda** format ;then how can I use it? And what will be the format of the downscaled output?

**Comment by jameshiebert** [comment]
I'm not familiar w/ .rda format. To use this package you'll have to convert them to NetCDF (which is the input *and* output format).
